import { Voter } from "./votingTypes";

export const voters: Voter[] = [
  {
    id: 1,
    state: "UP",
    district: "Lucknow",
    ageGroup: "18-25",
    gender: "Male",
    caste: "OBC",
    income: "Low",
    education: "Graduate",
    party: "BJP",
    year: 2024,
  },
  {
    id: 2,
    state: "UP",
    district: "Kanpur",
    ageGroup: "26-40",
    gender: "Female",
    caste: "SC",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2024,
  },
  {
    id: 3,
    state: "MH",
    district: "Mumbai",
    ageGroup: "26-40",
    gender: "Male",
    caste: "General",
    income: "High",
    education: "Post-Graduate",
    party: "AAP",
    year: 2023,
  },
  {
    id: 4,
    state: "MH",
    district: "Pune",
    ageGroup: "41-60",
    gender: "Female",
    caste: "OBC",
    income: "Middle",
    education: "Graduate",
    party: "BJP",
    year: 2022,
  },
  {
    id: 5,
    state: "RJ",
    district: "Jaipur",
    ageGroup: "18-25",
    gender: "Male",
    caste: "ST",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2021,
  },
  {
    id: 6,
    state: "DL",
    district: "South Delhi",
    ageGroup: "26-40",
    gender: "Female",
    caste: "General",
    income: "High",
    education: "Post-Graduate",
    party: "AAP",
    year: 2024,
  },
  {
    id: 7,
    state: "KA",
    district: "Bangalore",
    ageGroup: "41-60",
    gender: "Male",
    caste: "OBC",
    income: "High",
    education: "Graduate",
    party: "BJP",
    year: 2023,
  },
  {
    id: 8,
    state: "KA",
    district: "Mysore",
    ageGroup: "18-25",
    gender: "Female",
    caste: "SC",
    income: "Low",
    education: "School",
    party: "NOTA",
    year: 2022,
  },
  {
    id: 9,
    state: "DL",
    district: "East Delhi",
    ageGroup: "60+",
    gender: "Male",
    caste: "General",
    income: "Middle",
    education: "Graduate",
    party: "BJP",
    year: 2020,
  },
  {
    id: 10,
    state: "RJ",
    district: "Udaipur",
    ageGroup: "26-40",
    gender: "Other",
    caste: "ST",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2023,
  },
    {
    id: 11,
    state: "UP",
    district: "Lucknow",
    ageGroup: "18-25",
    gender: "Male",
    caste: "OBC",
    income: "Low",
    education: "Graduate",
    party: "BJP",
    year: 2024,
  },
  {
    id: 12,
    state: "UP",
    district: "Kanpur",
    ageGroup: "26-40",
    gender: "Female",
    caste: "SC",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2024,
  },
  {
    id: 13,
    state: "MH",
    district: "Mumbai",
    ageGroup: "26-40",
    gender: "Male",
    caste: "General",
    income: "High",
    education: "Post-Graduate",
    party: "AAP",
    year: 2023,
  },
  {
    id: 14,
    state: "MH",
    district: "Pune",
    ageGroup: "41-60",
    gender: "Female",
    caste: "OBC",
    income: "Middle",
    education: "Graduate",
    party: "BJP",
    year: 2022,
  },
  {
    id: 15,
    state: "RJ",
    district: "Jaipur",
    ageGroup: "18-25",
    gender: "Male",
    caste: "ST",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2021,
  },
  {
    id: 16,
    state: "DL",
    district: "South Delhi",
    ageGroup: "26-40",
    gender: "Female",
    caste: "General",
    income: "High",
    education: "Post-Graduate",
    party: "AAP",
    year: 2024,
  },
  {
    id: 17,
    state: "KA",
    district: "Bangalore",
    ageGroup: "41-60",
    gender: "Male",
    caste: "OBC",
    income: "High",
    education: "Graduate",
    party: "BJP",
    year: 2023,
  },
  {
    id: 18,
    state: "KA",
    district: "Mysore",
    ageGroup: "18-25",
    gender: "Female",
    caste: "SC",
    income: "Low",
    education: "School",
    party: "NOTA",
    year: 2022,
  },
  {
    id: 19,
    state: "DL",
    district: "East Delhi",
    ageGroup: "60+",
    gender: "Male",
    caste: "General",
    income: "Middle",
    education: "Graduate",
    party: "BJP",
    year: 2020,
  },
  {
    id: 20,
    state: "RJ",
    district: "Udaipur",
    ageGroup: "26-40",
    gender: "Other",
    caste: "ST",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2023,
  },
    {
    id: 21,
    state: "UP",
    district: "Lucknow",
    ageGroup: "18-25",
    gender: "Male",
    caste: "OBC",
    income: "Low",
    education: "Graduate",
    party: "BJP",
    year: 2024,
  },
  {
    id: 22,
    state: "UP",
    district: "Kanpur",
    ageGroup: "26-40",
    gender: "Female",
    caste: "SC",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2024,
  },
  {
    id: 23,
    state: "MH",
    district: "Mumbai",
    ageGroup: "26-40",
    gender: "Male",
    caste: "General",
    income: "High",
    education: "Post-Graduate",
    party: "AAP",
    year: 2023,
  },
  {
    id: 24,
    state: "MH",
    district: "Pune",
    ageGroup: "41-60",
    gender: "Female",
    caste: "OBC",
    income: "Middle",
    education: "Graduate",
    party: "BJP",
    year: 2022,
  },
  {
    id: 25,
    state: "RJ",
    district: "Jaipur",
    ageGroup: "18-25",
    gender: "Male",
    caste: "ST",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2021,
  },
  {
    id: 26,
    state: "DL",
    district: "South Delhi",
    ageGroup: "26-40",
    gender: "Female",
    caste: "General",
    income: "High",
    education: "Post-Graduate",
    party: "AAP",
    year: 2024,
  },
  {
    id: 27,
    state: "KA",
    district: "Bangalore",
    ageGroup: "41-60",
    gender: "Male",
    caste: "OBC",
    income: "High",
    education: "Graduate",
    party: "BJP",
    year: 2023,
  },
  {
    id: 28,
    state: "KA",
    district: "Mysore",
    ageGroup: "18-25",
    gender: "Female",
    caste: "SC",
    income: "Low",
    education: "School",
    party: "NOTA",
    year: 2022,
  },
  {
    id: 29,
    state: "DL",
    district: "East Delhi",
    ageGroup: "60+",
    gender: "Male",
    caste: "General",
    income: "Middle",
    education: "Graduate",
    party: "BJP",
    year: 2020,
  },
  {
    id: 30,
    state: "RJ",
    district: "Udaipur",
    ageGroup: "26-40",
    gender: "Other",
    caste: "ST",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2023,
  },
    {
    id: 31,
    state: "UP",
    district: "Lucknow",
    ageGroup: "18-25",
    gender: "Male",
    caste: "OBC",
    income: "Low",
    education: "Graduate",
    party: "BJP",
    year: 2024,
  },
  {
    id: 32,
    state: "UP",
    district: "Kanpur",
    ageGroup: "26-40",
    gender: "Female",
    caste: "SC",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2024,
  },
  {
    id: 33,
    state: "MH",
    district: "Mumbai",
    ageGroup: "26-40",
    gender: "Male",
    caste: "General",
    income: "High",
    education: "Post-Graduate",
    party: "AAP",
    year: 2023,
  },
  {
    id: 34,
    state: "MH",
    district: "Pune",
    ageGroup: "41-60",
    gender: "Female",
    caste: "OBC",
    income: "Middle",
    education: "Graduate",
    party: "BJP",
    year: 2022,
  },
  {
    id: 35,
    state: "RJ",
    district: "Jaipur",
    ageGroup: "18-25",
    gender: "Male",
    caste: "ST",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2021,
  },
  {
    id: 36,
    state: "DL",
    district: "South Delhi",
    ageGroup: "26-40",
    gender: "Female",
    caste: "General",
    income: "High",
    education: "Post-Graduate",
    party: "AAP",
    year: 2024,
  },
  {
    id: 37,
    state: "KA",
    district: "Bangalore",
    ageGroup: "41-60",
    gender: "Male",
    caste: "OBC",
    income: "High",
    education: "Graduate",
    party: "BJP",
    year: 2023,
  },
  {
    id: 38,
    state: "KA",
    district: "Mysore",
    ageGroup: "18-25",
    gender: "Female",
    caste: "SC",
    income: "Low",
    education: "School",
    party: "NOTA",
    year: 2022,
  },
  {
    id: 39,
    state: "DL",
    district: "East Delhi",
    ageGroup: "60+",
    gender: "Male",
    caste: "General",
    income: "Middle",
    education: "Graduate",
    party: "BJP",
    year: 2020,
  },
  {
    id: 40,
    state: "RJ",
    district: "Udaipur",
    ageGroup: "26-40",
    gender: "Other",
    caste: "ST",
    income: "Low",
    education: "School",
    party: "INC",
    year: 2023,
  },
];
